In [1]:
!pip install snowflake.connector-python pandas scikit-learn

Collecting snowflake.connector-python
  Downloading snowflake_connector_python-4.5.0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (84 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 84.8/84.8 kB 1.8 MB/s eta 0:00:00
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.12/dist-packages (1.6.1)
Collecting asn1crypto<2.0.0,>0.24.0 (from snowflake.connector-python)
  Downloading asn1crypto-1.5.1-py2.py3-none-any.whl.metadata (13 kB)
Collecting cryptography>=46.0.5 (from snowflake.connector-python)
  Downloading cryptography-48.0.0-cp311-abi3-manylinux_2_34_x86_64.whl.metadata (4.3 kB)
Requirement already satisfied: pyOpenSSL>=24.0.0 in /usr/local/lib/python3.12/dist-packages (from snowflake.connector-python) (24.2.1)
Requirement already satisfied: pyjwt<3.0.0,>=2.10.1 in /usr/local/lib/python3.12/dist-packages (from snowflake.connector-python) (2.12.1)
Requirement already satisfied: pytz in /usr/local/lib/python3.12/dist-packages (from snowflake.connector-python) (2025.2)
Requirement already satisfied: requests<3.0.0,>=2.32.4 in /usr/local/lib/python3.12/dist-packages (from snowflake.connector-python) (2.32.4)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from snowflake.connector-python) (26.1)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from snowflake.connector-python) (3.4.7)
Requirement already satisfied: idna<4,>=3.7 in /usr/local/lib/python3.12/dist-packages (from snowflake.connector-python) (3.13)
Requirement already satisfied: certifi>=2024.7.4 in /usr/local/lib/python3.12/dist-packages (from snowflake.connector-python) (2026.4.22)
Requirement already satisfied: typing_extensions<5,>=4.3 in /usr/local/lib/python3.12/dist-packages (from snowflake.connector-python) (4.15.0)
Requirement already satisfied: filelock<4,>=3.5 in /usr/local/lib/python3.12/dist-packages (from snowflake.connector-python) (3.29.0)
Collecting sortedcontainers>=2.4.0 (from snowflake.connector-python)
  Downloading sortedcontainers-2.4.0-py2.py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: platformdirs<5.0.0,>=2.6.0 in /usr/local/lib/python3.12/dist-packages (from snowflake.connector-python) (4.9.6)
Requirement already satisfied: tomlkit in /usr/local/lib/python3.12/dist-packages (from snowflake.connector-python) (0.13.3)
Collecting boto3>=1.24 (from snowflake.connector-python)
  Downloading boto3-1.43.13-py3-none-any.whl.metadata (6.6 kB)
Collecting botocore>=1.24 (from snowflake.connector-python)
  Downloading botocore-1.43.13-py3-none-any.whl.metadata (5.6 kB)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.1)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (1.16.3)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (3.6.0)
Collecting jmespath<2.0.0,>=0.7.1 (from boto3>=1.24->snowflake.connector-python)
  Downloading jmespath-1.1.0-py3-none-any.whl.metadata (7.6 kB)
Collecting s3transfer<0.18.0,>=0.17.0 (from boto3>=1.24->snowflake.connector-python)
  Downloading s3transfer-0.17.0-py3-none-any.whl.metadata (1.7 kB)
Requirement already satisfied: urllib3!=2.2.0,<3,>=1.25.4 in /usr/local/lib/python3.12/dist-packages (from botocore>=1.24->snowflake.connector-python) (2.5.0)
Requirement already satisfied: cffi>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from cryptography>=46.0.5->snowflake.connector-python) (2.0.0)
INFO: pip is looking at multiple versions of pyopenssl to determine which version is compatible with other requirements. This could take a while.
Collecting pyOpenSSL>=24.0.0 (from snowflake.connector-python)
  Downloading pyopenssl-26.2.0-py3-none-any.whl.metadata (19 kB)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: pycparser in /usr/local/lib/python3.12/dist-packages (from cffi>=2.0.0->cryptography>=46.0.5->snowflake.connector-python) (3.0)
Downloading snowflake_connector_python-4.5.0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (2.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.9/2.9 MB 29.4 MB/s eta 0:00:00
Downloading asn1crypto-1.5.1-py2.py3-none-any.whl (105 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 105.0/105.0 kB 3.4 MB/s eta 0:00:00
Downloading boto3-1.43.13-py3-none-any.whl (140 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 140.5/140.5 kB 2.1 MB/s eta 0:00:00
Downloading botocore-1.43.13-py3-none-any.whl (15.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 15.1/15.1 MB 17.6 MB/s eta 0:00:00
Downloading cryptography-48.0.0-cp311-abi3-manylinux_2_34_x86_64.whl (4.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.7/4.7 MB 27.8 MB/s eta 0:00:00
Downloading pyopenssl-26.2.0-py3-none-any.whl (55 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 55.8/55.8 kB 1.1 MB/s eta 0:00:00
Downloading sortedcontainers-2.4.0-py2.py3-none-any.whl (29 kB)
Downloading jmespath-1.1.0-py3-none-any.whl (20 kB)
Downloading s3transfer-0.17.0-py3-none-any.whl (86 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 86.8/86.8 kB 1.7 MB/s eta 0:00:00
Installing collected packages: sortedcontainers, asn1crypto, jmespath, cryptography, botocore, s3transfer, pyOpenSSL, boto3, snowflake.connector-python
  Attempting uninstall: cryptography
    Found existing installation: cryptography 43.0.3
    Uninstalling cryptography-43.0.3:
      Successfully uninstalled cryptography-43.0.3
  Attempting uninstall: pyOpenSSL
    Found existing installation: pyOpenSSL 24.2.1
    Uninstalling pyOpenSSL-24.2.1:
      Successfully uninstalled pyOpenSSL-24.2.1
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
pydrive2 1.21.3 requires cryptography<44, but you have cryptography 48.0.0 which is incompatible.
pydrive2 1.21.3 requires pyOpenSSL<=24.2.1,>=19.1.0, but you have pyopenssl 26.2.0 which is incompatible.
Successfully installed asn1crypto-1.5.1 boto3-1.43.13 botocore-1.43.13 cryptography-48.0.0 jmespath-1.1.0 pyOpenSSL-26.2.0 s3transfer-0.17.0 snowflake.connector-python-4.5.0 sortedcontainers-2.4.0

In [2]:
import pandas as pd
import snowflake.connector
conn=snowflake.connector.connect(
    user='akshayabalu',
    password='Akshayabalu123.',
    account='VPBHANW-PV88725',
    warehouse='COMPUTE_WH',
    database='INSURANCE_CLAIM',
    schema='PUBLIC'
)
query='SELECT*FROM  "INSURANCE_CLAIM"."PUBLIC"."INSURANCE_CLAIM"'
df=pd.read_sql_query(query,conn)
conn.close()
print(df.head())

/tmp/ipykernel_426/674701907.py:12: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df=pd.read_sql_query(query,conn)

   MONTHS_AS_CUSTOMER  AGE  POLICY_NUMBER POLICY_BIND_DATE POLICY_STATE  \
0                 328   48         521585       2014-10-17           OH
1                 228   42         342868       2006-06-27           IN
2                 134   29         687698       2000-09-06           OH
3                 256   41         227811       1990-05-25           IL
4                 228   44         367455       2014-06-06           IL

  POLICY_CSL  POLICY_DEDUCTABLE  POLICY_ANNUAL_PREMIUM  UMBRELLA_LIMIT  \
0    250/500               1000                1406.91               0
1    250/500               2000                1197.22         5000000
2    100/300               2000                1413.14         5000000
3    250/500               2000                1415.74         6000000
4   500/1000               1000                1583.91         6000000

   INSURED_ZIP  ... POLICE_REPORT_AVAILABLE TOTAL_CLAIM_AMOUNT INJURY_CLAIM  \
0       466132  ...                     YES              71610         6510
1       468176  ...                       ?               5070          780
2       430632  ...                      NO              34650         7700
3       608117  ...                      NO              63400         6340
4       610706  ...                      NO               6500         1300

  PROPERTY_CLAIM VEHICLE_CLAIM  AUTO_MAKE  AUTO_MODEL AUTO_YEAR  \
0          13020         52080       Saab         92x      2004
1            780          3510   Mercedes        E400      2007
2           3850         23100      Dodge         RAM      2007
3           6340         50720  Chevrolet       Tahoe      2014
4            650          4550     Accura         RSX      2009

  FRAUD_REPORTED  _C39
0           True  None
1           True  None
2          False  None
3           True  None
4          False  None

[5 rows x 40 columns]

In [3]:
df.head()

,MONTHS_AS_CUSTOMER,AGE,POLICY_NUMBER,POLICY_BIND_DATE,POLICY_STATE,POLICY_CSL,POLICY_DEDUCTABLE,POLICY_ANNUAL_PREMIUM,UMBRELLA_LIMIT,INSURED_ZIP,...,POLICE_REPORT_AVAILABLE,TOTAL_CLAIM_AMOUNT,INJURY_CLAIM,PROPERTY_CLAIM,VEHICLE_CLAIM,AUTO_MAKE,AUTO_MODEL,AUTO_YEAR,FRAUD_REPORTED,_C39
0,328,48,521585,2014-10-17,OH,250/500,1000,1406.91,0,466132,...,YES,71610,6510,13020,52080,Saab,92x,2004,True,None
1,228,42,342868,2006-06-27,IN,250/500,2000,1197.22,5000000,468176,...,?,5070,780,780,3510,Mercedes,E400,2007,True,None
2,134,29,687698,2000-09-06,OH,100/300,2000,1413.14,5000000,430632,...,NO,34650,7700,3850,23100,Dodge,RAM,2007,False,None
3,256,41,227811,1990-05-25,IL,250/500,2000,1415.74,6000000,608117,...,NO,63400,6340,6340,50720,Chevrolet,Tahoe,2014,True,None
4,228,44,367455,2014-06-06,IL,500/1000,1000,1583.91,6000000,610706,...,NO,6500,1300,650,4550,Accura,RSX,2009,False,None

In [5]:
df.tail()

,MONTHS_AS_CUSTOMER,AGE,POLICY_NUMBER,POLICY_BIND_DATE,POLICY_STATE,POLICY_CSL,POLICY_DEDUCTABLE,POLICY_ANNUAL_PREMIUM,UMBRELLA_LIMIT,INSURED_ZIP,...,POLICE_REPORT_AVAILABLE,TOTAL_CLAIM_AMOUNT,INJURY_CLAIM,PROPERTY_CLAIM,VEHICLE_CLAIM,AUTO_MAKE,AUTO_MODEL,AUTO_YEAR,FRAUD_REPORTED,_C39
995,3,38,941851,1991-07-16,OH,500/1000,1000,1310.80,0,431289,...,?,87200,17440,8720,61040,Honda,Accord,2006,False,None
996,285,41,186934,2014-01-05,IL,100/300,1000,1436.79,0,608177,...,?,108480,18080,18080,72320,Volkswagen,Passat,2015,False,None
997,130,34,918516,2003-02-17,OH,250/500,500,1383.49,3000000,442797,...,YES,67500,7500,7500,52500,Suburu,Impreza,1996,False,None
998,458,62,533940,2011-11-18,IL,500/1000,2000,1356.92,5000000,441714,...,YES,46980,5220,5220,36540,Audi,A5,1998,False,None
999,456,60,556080,1996-11-11,OH,250/500,1000,766.19,0,612260,...,?,5060,460,920,3680,Mercedes,E400,2007,False,None

In [4]:
df.describe()

,MONTHS_AS_CUSTOMER,AGE,POLICY_NUMBER,POLICY_DEDUCTABLE,POLICY_ANNUAL_PREMIUM,UMBRELLA_LIMIT,INSURED_ZIP,capital-gains,capital-loss,INCIDENT_HOUR_OF_THE_DAY,NUMBER_OF_VEHICLES_INVOLVED,BODILY_INJURIES,WITNESSES,TOTAL_CLAIM_AMOUNT,INJURY_CLAIM,PROPERTY_CLAIM,VEHICLE_CLAIM,AUTO_YEAR
count,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1.000000e+03,1000.000000,1000.000000,1000.000000,1000.000000,1000.00000,1000.000000,1000.000000,1000.00000,1000.000000,1000.000000,1000.000000,1000.000000
mean,203.954000,38.948000,546238.648000,1136.000000,1256.406150,1.101000e+06,501214.488000,25126.100000,-26793.700000,11.644000,1.83900,0.992000,1.487000,52761.94000,7433.420000,7399.570000,37928.950000,2005.103000
std,115.113174,9.140287,257063.005276,611.864673,244.167395,2.297407e+06,71701.610941,27872.187708,28104.096686,6.951373,1.01888,0.820127,1.111335,26401.53319,4880.951853,4824.726179,18886.252893,6.015861
min,0.000000,19.000000,100804.000000,500.000000,433.330000,-1.000000e+06,430104.000000,0.000000,-111100.000000,0.000000,1.00000,0.000000,0.000000,100.00000,0.000000,0.000000,70.000000,1995.000000
25%,115.750000,32.000000,335980.250000,500.000000,1089.607500,0.000000e+00,448404.500000,0.000000,-51500.000000,6.000000,1.00000,0.000000,1.000000,41812.50000,4295.000000,4445.000000,30292.500000,2000.000000
50%,199.500000,38.000000,533135.000000,1000.000000,1257.200000,0.000000e+00,466445.500000,0.000000,-23250.000000,12.000000,1.00000,1.000000,1.000000,58055.00000,6775.000000,6750.000000,42100.000000,2005.000000
75%,276.250000,44.000000,759099.750000,2000.000000,1415.695000,0.000000e+00,603251.000000,51025.000000,0.000000,17.000000,3.00000,2.000000,2.000000,70592.50000,11305.000000,10885.000000,50822.500000,2010.000000
max,479.000000,64.000000,999435.000000,2000.000000,2047.590000,1.000000e+07,620962.000000,100500.000000,0.000000,23.000000,4.00000,2.000000,3.000000,114920.00000,21450.000000,23670.000000,79560.000000,2015.000000

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 40 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   MONTHS_AS_CUSTOMER           1000 non-null   int64
 1   AGE                          1000 non-null   int64
 2   POLICY_NUMBER                1000 non-null   int64
 3   POLICY_BIND_DATE             1000 non-null   object
 4   POLICY_STATE                 1000 non-null   object
 5   POLICY_CSL                   1000 non-null   object
 6   POLICY_DEDUCTABLE            1000 non-null   int64
 7   POLICY_ANNUAL_PREMIUM        1000 non-null   float64
 8   UMBRELLA_LIMIT               1000 non-null   int64
 9   INSURED_ZIP                  1000 non-null   int64
 10  INSURED_SEX                  1000 non-null   object
 11  INSURED_EDUCATION_LEVEL      1000 non-null   object
 12  INSURED_OCCUPATION           1000 non-null   object
 13  INSURED_HOBBIES              1000 non-null   object
 14  INSURED_RELATIONSHIP         1000 non-null   object
 15  capital-gains                1000 non-null   int64
 16  capital-loss                 1000 non-null   int64
 17  INCIDENT_DATE                1000 non-null   object
 18  INCIDENT_TYPE                1000 non-null   object
 19  COLLISION_TYPE               1000 non-null   object
 20  INCIDENT_SEVERITY            1000 non-null   object
 21  AUTHORITIES_CONTACTED        1000 non-null   object
 22  INCIDENT_STATE               1000 non-null   object
 23  INCIDENT_CITY                1000 non-null   object
 24  INCIDENT_LOCATION            1000 non-null   object
 25  INCIDENT_HOUR_OF_THE_DAY     1000 non-null   int64
 26  NUMBER_OF_VEHICLES_INVOLVED  1000 non-null   int64
 27  PROPERTY_DAMAGE              1000 non-null   object
 28  BODILY_INJURIES              1000 non-null   int64
 29  WITNESSES                    1000 non-null   int64
 30  POLICE_REPORT_AVAILABLE      1000 non-null   object
 31  TOTAL_CLAIM_AMOUNT           1000 non-null   int64
 32  INJURY_CLAIM                 1000 non-null   int64
 33  PROPERTY_CLAIM               1000 non-null   int64
 34  VEHICLE_CLAIM                1000 non-null   int64
 35  AUTO_MAKE                    1000 non-null   object
 36  AUTO_MODEL                   1000 non-null   object
 37  AUTO_YEAR                    1000 non-null   int64
 38  FRAUD_REPORTED               1000 non-null   bool
 39  _C39                         0 non-null      object
dtypes: bool(1), float64(1), int64(17), object(21)
memory usage: 305.8+ KB

In [7]:
df.isnull().sum()

MONTHS_AS_CUSTOMER                0
AGE                               0
POLICY_NUMBER                     0
POLICY_BIND_DATE                  0
POLICY_STATE                      0
POLICY_CSL                        0
POLICY_DEDUCTABLE                 0
POLICY_ANNUAL_PREMIUM             0
UMBRELLA_LIMIT                    0
INSURED_ZIP                       0
INSURED_SEX                       0
INSURED_EDUCATION_LEVEL           0
INSURED_OCCUPATION                0
INSURED_HOBBIES                   0
INSURED_RELATIONSHIP              0
capital-gains                     0
capital-loss                      0
INCIDENT_DATE                     0
INCIDENT_TYPE                     0
COLLISION_TYPE                    0
INCIDENT_SEVERITY                 0
AUTHORITIES_CONTACTED             0
INCIDENT_STATE                    0
INCIDENT_CITY                     0
INCIDENT_LOCATION                 0
INCIDENT_HOUR_OF_THE_DAY          0
NUMBER_OF_VEHICLES_INVOLVED       0
PROPERTY_DAMAGE                   0
BODILY_INJURIES                   0
WITNESSES                         0
POLICE_REPORT_AVAILABLE           0
TOTAL_CLAIM_AMOUNT                0
INJURY_CLAIM                      0
PROPERTY_CLAIM                    0
VEHICLE_CLAIM                     0
AUTO_MAKE                         0
AUTO_MODEL                        0
AUTO_YEAR                         0
FRAUD_REPORTED                    0
_C39                           1000
dtype: int64

In [14]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

categorical_columns = [
    'POLICY_NUMBER',
    'POLICY_STATE',
    'POLICY_ANNUAL_PREMIUM',
    'UMBRELLA_LIMIT',
    'INCIDENT_DATE',
    'INCIDENT_TYPE',
    'COLLISION_TYPE',
    'INCIDENT_SEVERITY',
    'AUTHORITIES_CONTACTED',
    'INCIDENT_STATE',
    'INCIDENT_CITY',
    'INCIDENT_LOCATION',
    'NUMBER_OF_VEHICLES_INVOLVED',
    'PROPERTY_DAMAGE',
    'BODILY_INJURIES',
    'WITNESSES',
    'POLICE_REPORT_AVAILABLE',
    'TOTAL_CLAIM_AMOUNT',
    'INJURY_CLAIM',
    'PROPERTY_CLAIM',
    'VEHICLE_CLAIM',
    'AUTO_MAKE',
    'AUTO_MODEL',
    'AUTO_YEAR',
    'FRAUD_REPORTED',
]

for col in categorical_columns:
    df[col] = le.fit_transform(df[col].astype(str))

print(df.head())

KeyError: 'incident_state'

In [15]:
x=pd.DataFrame(df,columns=[ 'POLICY_NUMBER','POLICY_STATE','POLICY_ANNUAL_PREMIUM','UMBRELLA_LIMIT','INCIDENT_DATE','INCIDENT_TYPE','COLLISION_TYPE',
    'INCIDENT_SEVERITY','AUTHORITIES_CONTACTED','INCIDENT_STATE','INCIDENT_CITY','INCIDENT_LOCATION','NUMBER_OF_VEHICLES_INVOLVED','PROPERTY_DAMAGE',
    'BODILY_INJURIES','WITNESSES','POLICE_REPORT_AVAILABLE','TOTAL_CLAIM_AMOUNT','INJURY_CLAIM','PROPERTY_CLAIM','VEHICLE_CLAIM','AUTO_MAKE','AUTO_MODEL',
    'AUTO_YEAR','FRAUD_REPORTED'])
y=df['FRAUD_REPORTED'].values

In [10]:
from   sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=42)

In [11]:
from sklearn.impute import SimpleImputer
import numpy as np
x_train['POLICY_NUMBER'] = x_train['POLICY_NUMBER'].replace('N/A', np.nan).astype(float)
x_test['POLICY_NUMBER'] = x_test['POLICY_NUMBER'].replace('N/A', np.nan).astype(float)

imputer = SimpleImputer(strategy='mean')
x_train['POLICY_NUMBER'] = imputer.fit_transform(x_train[['POLICY_NUMBER']])
x_test['POLICY_NUMBER'] = imputer.transform(x_test[['POLICY_NUMBER']])

In [18]:
from sklearn.tree import DecisionTreeClassifier
import pandas as pd

# Apply one-hot encoding to X_train and X_test
x_train_encoded = pd.get_dummies(x_train, columns=['INCIDENT_STATE', 'INCIDENT_LOCATION', 'INCIDENT_SEVERITY'], drop_first=True)
x_test_encoded = pd.get_dummies(x_test, columns=['INCIDENT_STATE', 'INCIDENT_LOCATION', 'INCIDENT_SEVERITY'], drop_first=True)

# Ensure columns are aligned after one-hot encoding, especially if some categories only appear in train or test set
# This step is crucial to prevent errors when X_test might have fewer columns than X_train after get_dummies
missing_cols_train = set(x_test_encoded.columns) - set(x_train_encoded.columns)
for c in missing_cols_train:
    x_train_encoded[c] = 0
missing_cols_test = set(x_train_encoded.columns) - set(x_test_encoded.columns)
for c in missing_cols_test:
    x_test_encoded[c] = 0

x_test_encoded = x_test_encoded[x_train_encoded.columns]

model= DecisionTreeClassifier(criterion = 'entropy')
model.fit(x_train_encoded,y_train)

/tmp/ipykernel_426/2809687582.py:12: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  x_train_encoded[c] = 0
/tmp/ipykernel_426/2809687582.py:12: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  x_train_encoded[c] = 0
/tmp/ipykernel_426/2809687582.py:12: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  x_train_encoded[c] = 0
/tmp/ipykernel_426/2809687582.py:12: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  x_train_encoded[c] = 0
/tmp/ipykernel_426/2809687582.py:12: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  x_train_encoded[c] = 0
/tmp/ipykernel_426/2809687582.py:12: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  x_train_encoded[c] = 0
/tmp/ipykernel_426/2809687582.py:12: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  x_train_encoded[c] = 0
/tmp/ipykernel_426/2809687582.py:12: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  x_train_encoded[c] = 0
/tmp/ipykernel_426/2809687582.py:12: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  x_train_encoded[c] = 0
/tmp/ipykernel_426/2809687582.py:12: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  x_train_encoded[c] = 0
/tmp/ipykernel_426/2809687582.py:12: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  x_train_encoded[c] = 0
/tmp/ipykernel_426/2809687582.py:12: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  x_train_encoded[c] = 0
/tmp/ipykernel_426/2809687582.py:12: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  x_train_encoded[c] = 0
/tmp/ipykernel_426/2809687582.py:12: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  x_train_encoded[c] = 0
/tmp/ipykernel_426/2809687582.py:12: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  x_train_encoded[c] = 0
/tmp/ipykernel_426/2809687582.py:12: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  x_train_encoded[c] = 0
/tmp/ipykernel_426/2809687582.py:12: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  x_train_encoded[c] = 0
/tmp/ipykernel_426/2809687582.py:12: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  x_train_encoded[c] = 0
/tmp/ipykernel_426/2809687582.py:12: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  x_train_encoded[c] = 0
/tmp/ipykernel_426/2809687582.py:12: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  x_train_encoded[c] = 0
/tmp/ipykernel_426/2809687582.py:12: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  x_train_encoded[c] = 0
/tmp/ipykernel_426/2809687582.py:12: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  x_train_encoded[c] = 0
/tmp/ipykernel_426/2809687582.py:12: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  x_train_encoded[c] = 0
/tmp/ipykernel_426/2809687582.py:12: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  x_train_encoded[c] = 0
/tmp/ipykernel_426/2809687582.py:12: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  x_train_encoded[c] = 0
/tmp/ipykernel_426/2809687582.py:12: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  x_train_encoded[c] = 0
/tmp/ipykernel_426/2809687582.py:12: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  x_train_encoded[c] = 0
/tmp/ipykernel_426/2809687582.py:12: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  x_train_encoded[c] = 0
/tmp/ipykernel_426/2809687582.py:12: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  x_train_encoded[c] = 0
/tmp/ipykernel_426/2809687582.py:12: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  x_train_encoded[c] = 0
/tmp/ipykernel_426/2809687582.py:12: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  x_train_encoded[c] = 0
/tmp/ipykernel_426/2809687582.py:12: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  x_train_encoded[c] = 0
/tmp/ipykernel_426/2809687582.py:12: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  x_train_encoded[c] = 0
/tmp/ipykernel_426/2809687582.py:12: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  x_train_encoded[c] = 0
/tmp/ipykernel_426/2809687582.py:12: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  x_train_encoded[c] = 0
/tmp/ipykernel_426/2809687582.py:12: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  x_train_encoded[c] = 0
/tmp/ipykernel_426/2809687582.py:12: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  x_train_encoded[c] = 0
/tmp/ipykernel_426/2809687582.py:12: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  x_train_encoded[c] = 0
/tmp/ipykernel_426/2809687582.py:12: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  x_train_encoded[c] = 0
/tmp/ipykernel_426/2809687582.py:12: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  x_train_encoded[c] = 0
/tmp/ipykernel_426/2809687582.py:12: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  x_train_encoded[c] = 0
/tmp/ipykernel_426/2809687582.py:12: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  x_train_encoded[c] = 0
/tmp/ipykernel_426/2809687582.py:12: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  x_train_encoded[c] = 0
/tmp/ipykernel_426/2809687582.py:12: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  x_train_encoded[c] = 0
/tmp/ipykernel_426/2809687582.py:12: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  x_train_encoded[c] = 0
/tmp/ipykernel_426/2809687582.py:12: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  x_train_encoded[c] = 0
/tmp/ipykernel_426/2809687582.py:12: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  x_train_encoded[c] = 0
/tmp/ipykernel_426/2809687582.py:12: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  x_train_encoded[c] = 0
/tmp/ipykernel_426/2809687582.py:12: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  x_train_encoded[c] = 0
/tmp/ipykernel_426/2809687582.py:12: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  x_train_encoded[c] = 0
/tmp/ipykernel_426/2809687582.py:12: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  x_train_encoded[c] = 0
/tmp/ipykernel_426/2809687582.py:12: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  x_train_encoded[c] = 0
/tmp/ipykernel_426/2809687582.py:12: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  x_train_encoded[c] = 0
/tmp/ipykernel_426/2809687582.py:12: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  x_train_encoded[c] = 0
/tmp/ipykernel_426/2809687582.py:12: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  x_train_encoded[c] = 0
/tmp/ipykernel_426/2809687582.py:12: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  x_train_encoded[c] = 0
/tmp/ipykernel_426/2809687582.py:12: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  x_train_encoded[c] = 0
/tmp/ipykernel_426/2809687582.py:12: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  x_train_encoded[c] = 0
/tmp/ipykernel_426/2809687582.py:12: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

DecisionTreeClassifier(criterion='entropy')